# configs/constants.yaml
physics:
  mu_m3_per_s2: 3.986004418e+14  # 지구 중력 매개변수 [m^3/s^2]
  R_e_m: 6378140.0               # 지구 적도 반지름 [m] 
  J_2: 1.08263e-3                # 지구 편평도 계수
  g_e_m_per_s2: 9.80665          # 표준 중력 가속도 [m/s^2]

atmosphere:
  h_0: 200.0                     # 기준고도 [km]
  rho_0: 2.789e-10               # 기준밀도 [kg/m^3]
  H: 37.533                      # 척도고도 [km]