# configs/vehicle.yaml
propulsion:
  T_max_N: 0.021 # 최대 추력 [N] (21 mN)
  I_sp_s: 2000.0 # 비추력 [s]
  m_0_kg: 400.0  # 초기 질량 [kg] (wet mass)
  C_D: 2.2       # 항력 계수
  S_m2: 8.0      # 단면적 [m^2]
  
  propellant_mass_kg: 100.0